name: 自动发布 i18n-extension 版本
run-name: ${{ github.actor }} 正在发布 i18n-extension 版本
on:
  release:
    branches:
      - main
jobs:
  build-package:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 16.14.2
          cache: npm
      - run: npm ci
      - run: npm run package
